### ISSUE TITLE
Update documentation to describe EFI boot flow

### ISSUE THREAD

**Issue by ChinHuatAng** [intel/meta-acrn#19]
The documentation should mentioned that we currently rely on acrn-efi-setup which requires a reboot to get ACRN up and running.

**Comment by saininav** [comment]
With grub-efi bootloader and new wks source plugin, acrn-efi-setup is not required anymore. Already dropped from master. 
https://github.com/intel/meta-acrn/commit/3154d15108dcbad55fb4e58d89814724f1f8612b

Closing this issue.
