### ISSUE TITLE
Enable SBL support

### ISSUE THREAD

**Issue by rossburton** [intel/meta-acrn#2]
Building for Slim Bootloader instead of EFI doesn't work currently.

**Comment by cheeyanglee** [comment]
seems to be resolved since 1.6 onward.
added support for sbl image as well #182.

**Comment by saininav** [comment]
Support is available with below commits:
https://github.com/intel/meta-acrn/commit/c525ec965137f3b787ccec0d2270f4a9d4bbbfec
https://github.com/intel/meta-acrn/commit/d89c34519033714d7186013c3d50e4148649e255
