### ISSUE TITLE
We're going to have ACPICA pain again

### ISSUE THREAD

**Issue by rossburton** [intel/meta-acrn#29]
As per https://github.com/projectacrn/acrn-hypervisor/pull/3935 we're going to need to bump acpica release when we move to acrn 1.4.

**Comment by fuzhongl** [comment]
@rossburton Clear Linux update iasl version in their rootfs, so acrn-dm update it also.
Please use the latest CL build which included the commit of acrn-dm(coming soon).
Thanks

**Comment by rossburton** [comment]
This is the Yocto Project build, so we're not going to use Clear Linux builds.

**Comment by fuzhongl** [comment]
@rossburton  Please update iasl to 20191018 version for Yocto Project build.
Thanks!

**Comment by saininav** [comment]
Ross sent patch  to OE-core for 20191018 version.
http://lists.openembedded.org/pipermail/openembedded-core/2019-November/288939.html

**Comment by cheeyanglee** [comment]
acpica_20190816 in poky zeus works with acrn 1.3 but acpica_20191018 in master doesn't.

**Comment by fuzhongl** [comment]
@cheeyanglee Could you please share the error log?
Thanks!

**Comment by cheeyanglee** [comment]
@fuzhongl 
the output from launch-base.sh

cpu1 online=1
cpu2 online=1
cpu3 online=1
SW_LOAD: get kernel path /var/lib/machines/core-image-base.bzImage
SW_LOAD: get bootargs root=/dev/vda rw rootwait maxcpus=1 nohpet console=tty0 console=hvc0   console=ttyS0 no_timer_check ignore_loglevel log_buf_len=16M   consoleblank=0 tsc=reliable
vm_create: vm1
VHM api version 1.0
vm_setup_memory: size=0x80000000
open hugetlbfs file /run/hugepage/acrn/huge_lv1/vm1/D279543825D611E8864ECB7A18B34643
open hugetlbfs file /run/hugepage/acrn/huge_lv2/vm1/D279543825D611E8864ECB7A18B34643
level 0 free/need pages:0/0 page size:0x200000
level 1 free/need pages:0/2 page size:0x40000000
to reserve more free pages:
to reserve pages (+orig 0): echo 2 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
now enough free pages are reserved!

try to setup hugepage with:
	level 0 - lowmem 0x0, biosmem 0x0, highmem 0x0
	level 1 - lowmem 0x80000000, biosmem 0x0, highmem 0x0
total_size 0x180000000

mmap ptr 0x0x7f25129be000 -> baseaddr 0x0x7f2540000000
mmap 0x80000000@0x7f2540000000
touch 2 pages with pagesz 0x40000000

really setup hugepage with:
	level 0 - lowmem 0x0, biosmem 0x0, highmem 0x0
	level 1 - lowmem 0x80000000, biosmem 0x0, highmem 0x0
vm_init_vdevs
No correct pm notify channel given
pci init hostbridge
pci init lpc
pci init virtio-blk
polling 33...
Listening 33...
pci init virtio-net
pci init virtio-console
***********************************************
virt-console backend redirected to /dev/pts/0
***********************************************
pci init virtio-hyper_dmabuf
tpm: init_vtpm2:Invalid socket path!
acpi_build failed, error=-1
pci deinit hostbridge
pci deinit lpc
pci deinit virtio-blk
pci deinit virtio-net
vtnet tx thread closing...
pci deinit virtio-console
pci deinit virtio-hyper_dmabuf
mngr_client_new: Failed to accept from fd 33, err: Invalid argument
Stop listening 33...
Stop polling 33...
No correct pm notify channel given

**Comment by fuzhongl** [comment]
@cheeyanglee 
acrn-dm  master branch support acpica_20190816 and acpica_20191018; Could you please share your commit id about your master branch?
Thanks!

**Comment by saininav** [comment]
This issue has been fixed as yocto oe-core has required version.
