### ISSUE TITLE
Remove kernel config and use kernel config fragments instead

### ISSUE THREAD

**Issue by rossburton** [intel/meta-acrn#3]
Instead of shipping monolithic kernel configs for the UOS and SOS kernels, we should identify what *actually* needs to be enabled for the SOS and UOS, write kernel config fragments for those, and build a kernel based on the `linux-intel` recipe with these additional fragments.

##  SOS

* ACRN host-side virtio drivers
* ACRN options

## UOS

* More virtio devices (extend `cfg/virtio.cfg`)
* GVT-g
* Any ACRN-specific guest drivers

**Comment by cheeyanglee** [comment]
These would build kernel based on linux-intel 4.19 and apply config fragment with ACRN options, ACRN bridge and GVT.  

UOS kernel to linux-intel 
https://github.com/cheeyanglee/meta-acrn/commit/56e977d1011ed28022c9e1c525e40ca2b2fed150

SOS kernel to linux-intel 
https://github.com/cheeyanglee/meta-acrn/commit/11b5a116d85bc6a6c9c23b06dd200e814fa21861

**Comment by rossburton** [comment]
Looks like a step in the right direction.  Not entirely sure about the variable used to control the kernel configuration but need to think more on that.

Can you submit a proper pull request?

**Comment by saininav** [comment]
Lets merge Chee Yang's patches first. Later I will update my patch accordingly.

**Comment by saininav** [comment]
As Ross mentioned on my pull request https://github.com/intel/meta-acrn/pull/27#issuecomment-548581706 , we should not use bbappend, as it will included in base recipe if anyone include meta-acrn layer, which is not supposed to happen. 

Can you drop your bbappend from your patch and can raise pull request for v2.

**Comment by saininav** [comment]
Fix is merged https://github.com/intel/meta-acrn/commit/19d24d1dd7aed2449e3ad09cef23849bc9cfc220
