### ISSUE TITLE
'acrn-life-mngr.bb' recipe _looks_ broken

### ISSUE THREAD

**Issue by gvancuts** [intel/meta-acrn#311]
The recipe to build the ACRN `life_mngr` component _looks_ broken (although I have not verified it since I do not use Yocto :-))

See https://github.com/intel/meta-acrn/blob/master/recipes-core/acrn/acrn-life-mngr.bb and more specifically this line:
```
oe_runmake -C misc/life_mngr
```

The `life_mngr` folder was moved with https://github.com/projectacrn/acrn-hypervisor/commit/0ab5db9cf95c4f7a3f21051cb87b698aecf04210 and can now be found in `misc/services/life_mngr`

**Comment by saininav** [comment]
Fixed in master-next with https://github.com/intel/meta-acrn/commit/fa1f32a40f0c5f71cb64c21a694413451c2075b3.
