### ISSUE TITLE
Patch no longer needed? (add-fcommon-to-CFLAGS.patch)

### ISSUE THREAD

**Issue by gvancuts** [intel/meta-acrn#312]
The [following patch](https://github.com/intel/meta-acrn/blob/master/recipes-core/acrn/acrn-tools/add-fcommon-to-CFLAGS.patch) is likely no longer needed since https://github.com/projectacrn/acrn-hypervisor/commit/79892f911db93ddb724a83df098e5e37c806a961

**Comment by saininav** [comment]
@gvancuts Mater branch still have ACRN 2.3, which does not have https://github.com/projectacrn/acrn-hypervisor/commit/79892f911db93ddb724a83df098e5e37c806a961 commit.  We will drop it with 2.4 upgrade. 

If you are fine, then please close this issue.

**Comment by gvancuts** [comment]
Thanks @saininav , closing this!
