### ISSUE TITLE
Add stable release branch naming and update distro release version to match

### ISSUE THREAD

**Issue by moto-timo** [intel/meta-acrn#55]
Currently, we only have master branch with "warrior zeus" compatibility. We also have distro release version as 2.6, which was intentionally in sync with thud at the time the layer was first authored. We should create "warrior" branch (test it first on warrior layers), and update the distro version to 2.7. We should then create "zeus" branch, with distro release updated to 3.0. We should then update "master" to distro release 3.1.

**Comment by moto-timo** [comment]
So we already have the stable branch names for warrior and zeus. We just need to remember to bump the distro release version and the layer compatibility on master.

**Comment by saininav** [comment]
Agreed. Thanks Tim for raising this issue.

**Comment by saininav** [comment]
Merged patches.
master: https://github.com/intel/meta-acrn/commit/2c80263c940ae30af80c7c138c4f96a034a6bd92
zeus: https://github.com/intel/meta-acrn/commit/84fb8db64fa375d677367afffb9cf3c90c411ec9
warrior:https://github.com/intel/meta-acrn/commit/841e0fb85db4d3539c8b43cc2f7fcc63d7a3435d

**Comment by saininav** [comment]
Closing this issue.
