### ISSUE TITLE
Master branch does not build in a warrior build (+kernel commit not found)

### ISSUE THREAD

**Issue by salerio-gs** [intel/meta-acrn#62]
I notice that the master branch has **warrior** and **zeus** compatibility. However when the layer is used with poky/meta-intel warrior build **packagegroup-acrn.bb** generates an error.  I changed the inherit line to the following to fix it.

`inherit packagegroup distro_features_check`

Also the commit of linux-intel (which I'm guessing is to be found on the master branch of meta-intel) can't be found.

Maybe the layer should not be marked warrior compatible?

**Comment by saininav** [comment]
Thanks for reporting. We will fix this issue.

**Comment by saininav** [comment]
Fixed with https://github.com/intel/meta-acrn/commit/9c4d75c0fb93f089ebed45590128c238de300d76

**Comment by saininav** [comment]
Please reopen this bug, if still facing this issue. Now closing.
